name: PHP Lint

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'
                  coverage: none

            - name: Check PHP Version
              run: php -v

            - name: Lint PHP files
              run: find . -name "*.php" -print0 | xargs -0 -n1 php -l
